heat_template_version: 2016-04-08

parameters:
  server_image:
    description: ID or name of the glance image to boot from
    type: string
  ssh_key:
    description: ID or name of your ssh key. Must exist in your OpenStack account.
    type: string
  provider_network:
    description: ID or name of the external network
    type: string
  ipv6_subnetpool:
    description: ID or name of the subnet pool where you will get your public IPv6 subnet from
    type: string
  availability_zone:
    description: Availability Zone to spawn server in
    type: string

resources:
  dualstack_net:
    type: OS::Neutron::Net
    properties:
      name: heat_dualstack_net_centos

  ipv4_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: heat_ipv4_subnet_centos
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      network_id: { get_resource: dualstack_net }
      enable_dhcp: true
      ip_version: 4
      cidr: 10.100.0.0/16

  ipv6_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: heat_ipv6_subnet_centos
      dns_nameservers:
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      network_id: { get_resource: dualstack_net }
      enable_dhcp: true
      ip_version: 6
      ipv6_address_mode: dhcpv6-stateful
      ipv6_ra_mode: dhcpv6-stateful
      prefixlen: 64
      subnetpool:  { get_param: ipv6_subnetpool }

  dualstack_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { "network": { get_param: provider_network } }
      name: heat_dualstack_router_centos

  ipv4_router_interface:
    type: OS::Neutron::RouterInterface
    depends_on: ipv4_subnet
    properties:
      router_id: { get_resource: dualstack_router }
      subnet: { get_resource: ipv4_subnet }

  ipv6_router_interface:
    type: OS::Neutron::RouterInterface
    depends_on: ipv6_subnet
    properties:
      router_id: { get_resource: dualstack_router }
      subnet: { get_resource: ipv6_subnet }

  secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming ssh and icmp traffic from anywhere.
      name: heat_dualstack_icmp_ssh_centos
      rules:
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, port_range_max: 22, protocol: tcp, ethertype: IPv4 }
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp, ethertype: IPv4 }
        - { direction: ingress, remote_ip_prefix: "::/0", port_range_min: 22, port_range_max: 22, protocol: tcp, ethertype: IPv6 }
        - { direction: ingress, remote_ip_prefix: "::/0", protocol: ipv6-icmp, ethertype: IPv6 }

  dualstack_server:
    type: OS::Nova::Server
    depends_on:
      - ipv4_subnet
      - ipv6_subnet
    properties:
      image: { get_param: server_image }
      availability_zone: { get_param: availability_zone }
      flavor: m1.micro
      name: heat_dualstack_centos
      key_name: { get_param: ssh_key }
      security_groups:
        - { get_resource: secgrp }
      networks:
        - network: { get_resource: dualstack_net }
      user_data_format: RAW
      user_data: { get_resource: cloud_init_ipv6 }

  cloud_init_ipv6:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /etc/sysconfig/network
          owner: root:root
          permissions: '0644'
          content: |
              NETWORKING=yes
              NOZEROCONF=yes
              NETWORKING_IPV6=yes
        - path: /etc/sysconfig/network-scripts/ifcfg-eth0
          owner: root:root
          permissions: '0644'
          content: |
              DEVICE="eth0"
              BOOTPROTO="dhcp"
              ONBOOT="yes"
              TYPE="Ethernet"
              USERCTL="yes"
              PEERDNS="yes"
              PERSISTENT_DHCLIENT="1"
              IPV6INIT=yes
              DHCPV6C=yes
        runcmd:
          - [ ifdown, eth0]
          - [ ifup, eth0]
